const routes = {
  home: "/",
  about: "/about",
  capabilities: "/capabilities",
  serviceDetail: (slug: string) => `/capabilities/${slug}`,
  industry: "/industries",
  industryDetail: (slug: string) => `/industries/${slug}`,
  contact: "/contact-us",
  blog: "/blog",
  blogDetail: (slug: string) => `/insights/views/${slug}`,
  news: "/insights/news",
  newsDetails: (slug: string) => `/insights/news/${slug}`,
  events: "/insights/events",
  eventsDetail: (slug: string) => `/insights/events/${slug}`,
  policyDetails: (slug: string) => `/policy/${slug}`,
  caseStudies: `/insights/case-study`,
  caseStudyDetails: (slug: string) => `/insights/case-study/${slug}`,
  joinUs: "/career/join-us",
  joinDetails: (slug: string) => `/career/join-us/${slug}`,
  ourBrand: "/about/our-brand",
  brandSustainability: "/about/sustainability",
  brandLeadership: "/about/leadership",
  brandClientPortfolio: "/about/our-client-portfolio",
  brandAwards: "/about/awards-recognition",
  brandAllience: "/about/strategic-alliance",
  settings: "/settings",
};

export default routes;
